globals:
    # Device type ID
  - id: device_type
    type: int
    initial_value: '0'

    # Peak current on device startup
  - id: startup_peak
    type: float
    initial_value: '0.0'

    # Duration of starup until current stabilizes
  - id: startup_duration
    type: int
    initial_value: '0'

    # Average current while the device is running
  - id: steady_power
    type: float
    initial_value: '0.0'

    # Current signal variance
  - id: current_variance
    type: float
    initial_value: '0.0'

    # Current used while the device is off
  - id: phantom_power
    type: float
    initial_value: '0.0'

script:
  - id: analyze_device
    mode: restart
    then:
      - lambda: |-
          float max_i = 0;
          float sum_p = 0;
          float sum_sq_diff = 0;
          uint32_t start_time = millis();
          int samples = 0;

          // 1. Capture Inrush (1.5s window)
          // TODO: Check phantom power and detect when device is actually turned on for devices with a switch
          while (millis() - start_time < 1500) {
            float cur = id(bl0937_current).state;
            if (cur > max_i) max_i = cur;
            delay(50);
          }
          id(startup_peak) = max_i;
          id(startup_duration) = millis() - start_time;

          // 2. Steady State Analysis (2s window)
          uint32_t steady_mark = millis();
          while (millis() - steady_mark < 2000) {
            float p = id(bl0937_power).state;
            sum_p += p;
            samples++;

            float mean = sum_p / samples;
            sum_sq_diff += pow(p - mean, 2);
            delay(100);
          }

          id(steady_pwr) = sum_p / samples;
          id(current_var) = sum_sq_diff / samples;

          // Update template sensors
          id(ai_peak).publish_state(id(startup_peak));
          id(ai_duration).publish_state(id(startup_duration));
          id(ai_variance).publish_state(id(current_var));

          ESP_LOGI("SmartPlug", "Analysis Complete: Peak=%.2fA, Var=%.4f", id(startup_peak), id(current_var));
