# -------------------------------------
# ESPHome settings
# -------------------------------------

esphome:
  name: emax
  friendly_name: EMAX

bk72xx:
  board: cb2s

# Enable logging
logger:

# Enable Home Assistant API
# api:
#   encryption:
#     key: !secret encryption_key

ota:
  - platform: esphome
    password: !secret ota_password
  - platform: web_server

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

  manual_ip:
    # Set this to the IP of the ESP
    static_ip: 10.87.169.42
    # Set this to the IP address of the router. Often ends with .1
    gateway: 127.0.0.1
    # The subnet of the network. 255.255.255.0 works for most home networks.
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Emax Fallback Hotspot"
    password: !secret ap_password

captive_portal:

web_server:
  port: 80
  include_internal: true
  version: 3

text_sensor:
  - platform: libretiny
    version:
      name: LibreTiny Version

# Use the modified hlw8012 component
external_components:
 - source:
     type: local
     path: components

# -------------------------------------
# Outlet components
# -------------------------------------
binary_sensor:
  - platform: gpio
    id: binary_switch_1
    pin:
      number: 6
      inverted: true
      mode: INPUT_PULLUP
    on_press:
      then:
        - switch.toggle: switch_1

switch:
  - platform: gpio
    id: switch_1
    name: "Relay 1"
    pin: 8
    on_turn_off:
          then:
            - lambda: |-
                id(device_running) = false;
                id(in_startup) = false;
                id(avg_power) = 0.0f;
                id(avg_current) = 0.0f;

status_led:
  pin:
    number: 7
    inverted: true


# -------------------------------------
# Substitutions
# -------------------------------------
substitutions:
  outlet_power_subtract: 4.82
  outlet_current_subtract: 0.02
  startup_threshold: 0.05
  # EMA alpha — tune for smoothing vs responsiveness
  avg_alpha: 0.1

# -------------------------------------
# Globals
# -------------------------------------
globals:
  - id: device_running
    type: bool
    initial_value: "false"

  - id: in_startup
    type: bool
    initial_value: "false"

  - id: startup_max_current
    type: float
    initial_value: "0.0"

  - id: avg_power
    type: float
    initial_value: "0.0"

  - id: avg_current
    type: float
    initial_value: "0.0"

  - id: last_power
    type: float
    initial_value: "0.0"

  - id: phantom_power
    type: float
    initial_value: "0.0"

  - id: max_variance
    type: float
    initial_value: "0.0"

number:
  - platform: template
    name: "Emergency Stop Power"
    id: emergency_stop_power
    optimistic: true
    min_value: 0
    max_value: 3500
    step: 10
    initial_value: 2500
    unit_of_measurement: "W"
    mode: BOX # Or SLIDER

select:
  - platform: template
    name: "Device Type"
    id: device_type
    optimistic: true
    options:
      - "Heater"
      - "PC"
      - "Washing Machine"
      - "Phone Charger"
      - "Mixer"
      - "Hair Dryer"
      - "Lamp"
      - "Unknown"
    initial_option: "Other"
# -------------------------------------
# Sensor
# -------------------------------------
sensor:
  - platform: hlw8012
    model: BL0937
    id: hlw_hub
    cf_pin:
      number: P24
      inverted: true
    cf1_pin:
      number: P26
      inverted: true
    sel_pin:
      number: P10
      inverted: true
    voltage_divider: 698.69
    change_mode_every: 8
    current:
      name: Current
      id: current
      accuracy_decimals: 3
      filters:
        - multiply: 0.39
    voltage:
      name: Voltage
      id: voltage
      accuracy_decimals: 2
      filters:
        - multiply: 1.15
    power:
      name: Power
      id: power
      accuracy_decimals: 2
      on_value:
        then:
          - lambda: |-
              if(!id(switch_1).state) return;
              
              if (x > id(emergency_stop_power).state) {
                id(switch_1).turn_off();
                ESP_LOGE("emax", "EMERGENCY STOP: Power %.2fW exceeded limit!", x);
                return; 
              }

              float p =  x - ${outlet_power_subtract};
              float power_difference = std::abs(x - id(last_power));
              id(last_power) = x;

              // Logic when device is OFF
              if (!id(device_running)) {
                if(p > ${startup_threshold}) {
                  if(!id(in_startup)) {
                    id(startup_max_current) = p;
                    id(in_startup) = true;
                    ESP_LOGD("emax", "Startup detected");
                  }
                  else {
                    if(p > id(startup_max_current)) id(startup_max_current) = p;

                    // Transition to Running
                    if(power_difference < (0.25f * p)) {
                      id(in_startup) = false;
                      id(device_running) = true;
                      id(avg_power) = p;
                      id(avg_current) = id(current).state;
                    }
                  }
                }
                //else if (!id(in_startup)) {
                //  id(phantom_power) = p;
                //}
              }
              // Logic when device is RUNNING
              else {
                // Check if device was powered off
                if(p < (id(phantom_power) * 2.0f + 1.0f) && p != 0) {
                    id(device_running) = false;
                    id(max_variance) = 0;
                    ESP_LOGD("emax", "Device stopped");
                }
                // Calculate EMA averages
                else {
                  id(avg_power)   = (${avg_alpha} * x) + (1.0f - ${avg_alpha}) * id(avg_power);
                  id(avg_current) = (${avg_alpha} * id(current).state) + (1.0f - ${avg_alpha}) * id(avg_current);
                }
                // Calculate max variance
                if(power_difference > id(max_variance)) {
                  id(max_variance) = power_difference;
                }
              }


    energy:
      name: Energy
      accuracy_decimals: 2
    update_interval: 1000ms

    # Wi-fi signal
  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    update_interval: 60s

    # Analytics sensors

  - platform: template
    id: sensor_avg_power
    name: "Average Power"
    unit_of_measurement: "W"
    accuracy_decimals: 2
    icon: "mdi:lightning-bolt"
    update_interval: 2s
    lambda: |-
      return id(avg_power);

  - platform: template
    id: sensor_avg_current
    name: "Average Current"
    unit_of_measurement: "A"
    accuracy_decimals: 3
    icon: "mdi:current-ac"
    update_interval: 2s
    lambda: |-
      return id(avg_current);

  # - platform: template
  #   id: sensor_phase_angle
  #   name: "Phase Angle"
  #   unit_of_measurement: "°"
  #   accuracy_decimals: 1
  #   icon: "mdi:angle-acute"
  #   update_interval: 5s
  #   lambda: |-
  #     return id(avg_current)*id(voltage).state/id(avg_power);

  - platform: template
    id: sensor_phantom_power
    name: "Phantom Power"
    unit_of_measurement: "W"
    accuracy_decimals: 2
    icon: "mdi:ghost"
    update_interval: 5s
    lambda: |-
      return id(phantom_power);

  - platform: template
    id: sensor_startup_max_current
    name: "Startup Peak Current"
    unit_of_measurement: "A"
    accuracy_decimals: 3
    icon: "mdi:flash"
    update_interval: 5s
    lambda: |-
      return id(startup_max_current);

  - platform: template
    id: sensor_max_variance
    name: "Max Power Variance"
    unit_of_measurement: "W"
    accuracy_decimals: 3
    icon: "mdi:trending-up"
    update_interval: 5s
    lambda: |-
      return id(max_variance);